AmzCrawler/webserver/ams/models.py
import datetime

from ams import db

class Listing(db.Model):
    __tablename__ = 'listing'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    img = db.Column(db.String(250), default='')
    asin = db.Column(db.String(15), nullable=True)
    seller = db.Column(db.String(30), default='')
    status = db.Column(db.Integer, default=0)
    adtime = db.Column(db.DateTime, default=datetime.datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    __table_args__ = (
        # 联合唯一
        db.UniqueConstraint('asin', 'seller'),
    )


class Marks(db.Model):
    __tablename__ = 'marks'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    bsr = db.Column(db.Integer, nullable=False)
    price = db.Column(db.Integer, nullable=False)
    stock = db.Column(db.String(10), nullable=False)
    uptime = db.Column(db.DateTime, default=datetime.datetime.now)

    asin_id = db.Column(db.Integer, db.ForeignKey("listing.id"))

    listing = db.relationship("Listing", backref=db.backref('marks'))


class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    pwd = db.Column(db.String(40), nullable=True)
    name = db.Column(db.String(10), nullable=True, unique=True)

AmzCrawler/webserver/ams/__init__.py
from flask import Blueprint

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

ams = Blueprint(
    'ams',
    __name__,
    static_folder='assets',
    template_folder='templates'
)

from . import views


# ams1 = Blueprint(
#     'ams1',
#     __name__,
#     static_folder='assets1',
#     template_folder='templates1'
# )
#
# from ams import views1

AmzCrawler/webserver/ams/views.py
import os
from flask import render_template, jsonify, request, session, redirect, url_for
from ams.models import User, Listing, Marks
from configure import LOGS_PATH
from . import ams, db


@ams.before_request
def verify_login(*args, **kwargs):

    if request.path.strip('/') == 'login': return None
    if request.path.strip('/') == 'assets/css/layui.css': return None
    if session.get('user_id'): return None

    return redirect(url_for('ams.login'))


@ams.route('/logdel')
def logdel():
    trace = LOGS_PATH + "/trace.txt"
    other = LOGS_PATH + "/other.txt"

    # 判断文件是否存在
    if (os.path.exists(trace)):
        with open(trace, "r+") as f:
            f.truncate()

    if (os.path.exists(other)):
        with open(other, "r+") as f:
            f.truncate()

    # if (os.path.exists(other)):
    #     os.remove(other)

    return redirect(url_for('ams.index'))


#
@ams.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':

        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter(User.name == username, User.pwd == password).first()

        if user != None:
            session['user_id'] = user.id

            return redirect(url_for('ams.index'))

    if request.args.get('s') == '1':
        session.pop('user_id', None)

    if session.get('user_id'): return redirect(url_for('ams.index'))

    title = '登陆'
    return render_template('login.html', title=title)


#
@ams.route('/')
def index():
    title = '首页'

    curr = int(request.args.get('page')) if request.args.get('page') else 0

    ssub = db.session.query(Marks, db.func.max(Marks.uptime).label('sss')).group_by(Marks.asin_id).subquery()

    data = db.session.query((Listing.id).label('aid'), Listing.img, Listing.asin, Listing.adtime, ssub).join(ssub,
                                                                                                             isouter=True).order_by(
        Listing.adtime.desc()).limit(20).offset((curr-1)*20).all()


    coun = db.session.query(db.func.count(Listing.asin).label('count')).one()

    ss = {'title': title, 'data': data, 'curr': curr, 'count': coun[0]}

    return render_template('index.html', **ss)


#
@ams.route('/add', methods=['GET', 'POST'])
def add():

    # user = User(name='admin',pwd='1111')
    # db.session.add(user)
    # db.session.commit()

    if request.method == 'POST':

        asins = str(request.form.get('asins')).split('\n')
        asins = [tuple(i.strip().split('|')) for i in asins if i.strip() != '']
        asins = list(set(asins))

        rowss = []
        for row in asins:

            seller = row[1] if len(row) > 1 else ''

            if Listing.query.filter(Listing.asin == row[0], Listing.seller == seller).first():
                rowss.append(row)
                continue

            listing = Listing(asin=row[0], seller=seller, user_id=session.get('user_id'))

            db.session.add(listing)

        db.session.commit()

        return jsonify(rowss)

    title = '添加ASIN'
    return render_template('add.html', title=title)


#
@ams.route('/lists')
def lists():

    id = request.args.get('id')

    if id.isdigit() and int(id) > 0:
        data = db.session.query(Marks).filter(Marks.asin_id == id).order_by(Marks.asin_id.desc()).all()
    else:

        data = db.session.query(Marks).order_by(Marks.asin_id.desc()).all()

    title = '全部数据'

    return render_template('lists.html', title=title, data=data)


#
@ams.route('/export/<int:id>')
def export(id):
    from flask import make_response

    import tablib

    if id > 0:

        res = db.session.query(Marks).filter(Marks.asin_id == id).all()
    else:
        res = db.session.query(Marks).all()

    head = (u"ASIN", u"类目排名", u"价格", u"库存", u"查询时间")

    info = [(i.listing.asin, i.bsr, i.price, i.stock, i.uptime.strftime("%Y-%m-%d")) for i in res]

    data = tablib.Dataset(*info, headers=head)

    resp = make_response(data.xls)

    filename = 'amazon.xls'  # 用户下载默认文件名

    resp.headers["Content-Disposition"] = "attachment; filename=" + filename  # 指定响应为下载文件

    resp.headers['Content-Type'] = 'xls'  # 不指定的话会默认下载html格式，下载后还要改格式才能看

    return resp


#
@ams.route('/del/<int:id>')
def delasin(id):
    db.session.query(Listing).filter(Listing.id == id).delete()
    db.session.query(Marks).filter(Marks.asin_id == id).delete()

    db.session.commit()

    return redirect(url_for('ams.index'))


@ams.route('/drop')
def drop():

    db.drop_all()

    db.create_all()

    user = User(name='admin',pwd='11111')

    db.session.add(user)

    db.session.commit()

    return redirect(url_for('ams.add'))


@ams.route('/test')
def test():
    return render_template('a1.html')

AmzCrawler/webserver/ams/templates/add.html
{% extends 'base.html' %}

{% block main %}
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md8">
            <div class="layui-card">
                <div class="layui-card-header">添加ASIN</div>
                <div class="layui-card-body">

                    <form class="layui-form" method="post">

                        <div class="layui-form-item layui-form-text">
                            <textarea style="min-height: 500px" name="asins" placeholder="请输入内容每行一条 eg:ASIN|SellerID" class="layui-textarea" lay-verify="required"></textarea>
                        </div>
                        <div class="layui-form-item">
                            <button class="layui-btn" lay-submit lay-filter="add">立即提交</button>
                            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        layui.use('form', function(){
            var form = layui.form;
            form.on('submit(add)', function(data){
                var msg = '添加成功!'
                $.post('', data.field, function (res) {
                    if (res.length>0){
                        msg = '<strong>已删除以下重复信息!</strong><br>'
                        $.each(res,function (i,obj) {
                            if (obj.length == 2){
                                msg += obj[0]+':'+obj[1]+"<br>"
                            }else{
                                msg += obj[0]+"<br>"
                            }
                        })
                    }

                    layer.open({
                        title: '提示信息!',
                        content: msg,
                        yes: function(index, layero){
                            //do something
                            window.location.href='{{ url_for("ams.index") }}';
                        }

                    })
                })
                return false;
            })
        })
    </script>
{% endblock main %}

AmzCrawler/webserver/ams/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='assets/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='assets/css/layui.css') }}"  media="all">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{ url_for('static',filename='assets/layui.js') }}"></script>
</head>
<body>
<div class="layui-row">
    <ul class="layui-nav" lay-filter="">
        <li class="layui-nav-item {% if request.path == '/' %} layui-this {% endif %}"><a href="{{ url_for('ams.index',page=0) }}">首页</a></li>
        <li class="layui-nav-item {% if request.path == '/add' %} layui-this {% endif %}"><a href="{{ url_for('ams.add') }}">添加数据</a></li>
        <li class="layui-nav-item {% if request.path == '/export' %} layui-this {% endif %}"><a href="{{ url_for('ams.export', id='0') }}">导出全部</a></li>
        <li class="layui-nav-item">
            <a href="javascript:;">查看日志</a>
            <dl class="layui-nav-child">
              <dd><a target="_blank" href="{{ url_for('static', filename='assets/logs/trace.txt') }}">追踪日志</a></dd>
              <dd><a target="_blank" href="{{ url_for('static', filename='assets/logs/other.txt') }}">其他日志</a></dd>
              <dd><a href="{{ url_for('ams.logdel') }}">清空日志</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            {% if session.get('user_id')%}
                <a href="{{ url_for('ams.login') }}?s=1">退出</a>
            {% else %}
                <a href="{{ url_for('ams.login') }}">登陆</a>
            {% endif %}

        </li>
    </ul>
</div>

<div class="layui-fluid">
    <div class="layui-row">
        <div class="layui-col-md8">
            <div style="padding: 20px; background-color: #F2F2F2;">
                {% block main %}{% endblock %}
            </div>
        </div>
    </div>
</div>

</body>
</html>

<script>
    layui.use('element', function(){
        var element = layui.element; //导航的hover效果、二级菜单等功能，需要依赖element模块

        //监听导航点击
        element.on('nav(demo)', function(elem){
            //console.log(elem)
            layer.msg(elem.text());
        });
    });
</script>

AmzCrawler/webserver/ams/templates/index.html
{% extends 'base.html' %}

{% block main %}
    <table class="layui-table" style="margin: 0">
        <tbody>
        <tr>
            <td colspan="8">ASIN 列表  (系统每天凌晨1点25分定时抓取数据)</td>
            <td colspan="1"><a href="{{ url_for('ams.drop') }}" class="layui-btn layui-btn-sm">清空全部</a></td>
        </tr>
        <tr>
            <td width="20">序</td>
            <td width="50">图片</td>
            <td>Asin</td>
            <td>操作</td>
            <td>排名</td>
            <td>价格</td>
            <td>库存</td>
            <td width="150">最近查询时间</td>
            <td width="150">添加时间</td>
        </tr>

        {% for item in data %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{% if item.img %}<img src="{{ item.img }}" height="50">{% else %} 未抓取 {% endif %}</td>
            <td><a href="https://www.amazon.com/dp/{{item.asin}}" target="_blank" style="color:#1E9FFF">{{ item.asin }}</a></td>
            <td id="exe">
                <a href="{{url_for('ams.delasin', id=item.aid)}}" class="layui-btn layui-btn-xs layui-btn-normal">删除</a>
                <a href="{{url_for('ams.lists')}}?id={{item.aid}}" class="layui-btn layui-btn-xs">排名</a>
                <a href="{{url_for('ams.lists')}}?id={{item.aid}}" class="layui-btn layui-btn-xs">价格</a>
                <a href="{{url_for('ams.lists')}}?id={{item.aid}}" class="layui-btn layui-btn-xs layui-btn-danger">库存</a>
                {% if item.seller %}
                    <a target="_blank" href="https://www.amazon.com/shops/{{item.seller}}" class="layui-btn layui-btn-xs layui-btn-normal">店铺</a>
                {% endif %}
            </td>
            <td>{% if item.bsr %} {{ item.bsr }} {% endif %}</td>
            <td>{% if item.bsr %} {{ item.price }} {% endif %}</td>
            <td>{% if item.bsr %} {{ item.stock }} {% endif %}</td>
            <td>
                {% if item.uptime %}
                    {{item.uptime.strftime("%Y-%m-%d %H:%M:%S")}}
                {% endif %}
            </td>
            <td>
                {% if item.adtime %}
                    {{item.adtime.strftime("%Y-%m-%d %H:%M:%S")}}
                {% endif %}
            </td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
    <div id="demo0"></div>
    <script>
        layui.use('laypage', function(){
            var laypage = layui.laypage

            laypage.render(
            {
                elem: 'demo0',
                count: {{ count }},
                curr: {{ curr }},
                limit:20,
                jump: function(obj, first) {

                    if(!first) {

                        window.location.href = '{{ url_for("ams.index") }}?page='+ obj.curr
                    }
                }

            })
        })
    </script>








{% endblock main %}

AmzCrawler/webserver/ams/templates/lists.html
{% extends 'base.html' %}

{% block main %}


    <table class="layui-table" style="margin: 0">
        <tbody>
        <tr>
            <td colspan="6">ASIN 列表 </td>
            <td colspan="1"><a href="{{url_for('ams.export', id=request.args.get('id'))}}" class="layui-btn-sm layui-btn">导出</a></td>
        </tr>
        <tr>
            <td width="20">序</td>
            <td width="50">图片</td>
            <td>Asin</td>
            <td>排名</td>
            <td>价格</td>
            <td>库存</td>
            <td>查询时间</td>
        </tr>

        {% for item in data %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{% if item.listing.img %}<img src="{{ item.listing.img }}" height="50">{% else %} 未抓取 {% endif %}</td>
            <td><a href="https://www.amazon.com/dp/{{item.listing.asin}}" target="_blank" style="color:#1E9FFF">{{ item.listing.asin }}</a></td>
            <td>{{ item.bsr }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.stock }}</td>
            <td>{{ item.uptime.strftime("%Y-%m-%d %H:%M:%S") }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>



{% endblock main %}

AmzCrawler/webserver/ams/templates/login.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='/assets/css/layui.css') }}">
</head>
<body style="background: #f3f3f3;">

<div class="layui-fluid">
    <div class="layui-row">

        <form method="post" class="layui-form layui-col-md2" style="margin: 30px;">

            <div class="layui-form-item">
                <input type="text" name="username" lay-verify="required" placeholder="用户名" class="layui-input">
            </div>
            <div class="layui-form-item">
                <input type="password" name="password" lay-verify="required" placeholder="密码" class="layui-input">
            </div>

            <div class="layui-form-item">
                <button class="layui-btn layui-btn-fluid" lay-submit="" lay-filter="LAY-user-login-submit">登 入</button>
            </div>

        </form>
    </div>
</div>

</body>
</html>